services:
    app:
        image: masqueradisu/laravel-php:8.5-dev
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '../src:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
        container_name: ${APP_NAME}_app

    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - sail-pgsql:/var/lib/postgresql/data
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
        container_name: ${APP_NAME}_postgresql

    mailhog:
        image: 'mailhog/mailhog'
        ports:
            -   '${MAIL_PORT}:1025'
            -   '${MAIL_UI}:8025'
        container_name: ${APP_NAME}_mailhog
        networks:
            - sail

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        container_name: ${APP_NAME}_nginx
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            -   ../src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sail

    loki:
        image: grafana/loki:latest
        ports:
            - "3100:3100"
        volumes:
            - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - sail
        container_name: ${APP_NAME}_loki

    promtail:
        image: grafana/promtail:latest
        volumes:
            - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
            - ../src/storage/logs:/var/log/laravel
        command: -config.file=/etc/promtail/config.yml
        networks:
            - sail
        depends_on:
            - loki
        container_name: ${APP_NAME}_promtail

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        networks:
            - sail
        depends_on:
            - loki
        container_name: ${APP_NAME}_grafana

networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local

