name: Laravel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          extensions: pdo_pgsql, pgsql, mbstring, xml, ctype, iconv, intl

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        working-directory: ./src

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: src/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('src/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: ./src

      - name: Create .env file from secret
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Run test suite
        run: php artisan test --coverage
        working-directory: ./src
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: password
